### ISSUE TITLE
web-components | Handle Figma variables

### ISSUE THREAD

**Issue by r3dDoX** [Zuehlke/design-system-starter#5]
Figma Variables are currently being exported in the design-tokens.json as `constraints`.
Check out if there is a good way to handle them in style-dictionary so they get into our codebase like the other design-tokens

**Comment by culas** [comment]
Open questions: 
* how to have some tokens in pixels, instead of everything as rem (e.g. for border sizes)? 
* have generic sizes (e.g. `size-0-5`) in `constraints` or as "regular" tokes? currently both exist (check with UX)
